name: User Management
on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username to create"
        required: true
        type: string
      ssh_key:
        description: "SSH public key"
        required: true
        type: string
jobs:
  manage-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install ansible
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
      - env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: ansible-playbook main.yml -e "username=${{ inputs.username }} ssh_key='${{ inputs.ssh_key }}' bastion_host=${{ vars.BASTION }} ssh_key_path=~/.ssh/id_rsa"
      - run: ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.BASTION }} "id ${{ inputs.username }} && ls -la /home/${{ inputs.username }}/.ssh/authorized_keys"
      - if: always()
        run: rm -f ~/.ssh/id_rsa
