name: Ansible Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Ansible Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==8.5.0

      - name: Create test playbook
        run: |
          mkdir -p playbooks
          cat << EOF > playbooks/test.yml
          ---
          - name: Test Playbook
            hosts: localhost
            connection: local
            gather_facts: yes
            
            tasks:
              - name: Print system info
                debug:
                  msg: "Running on {{ ansible_distribution }} {{ ansible_distribution_version }}"
              
              - name: Create test directory
                file:
                  path: /tmp/ansible-test
                  state: directory
                  mode: '0755'
              
              - name: Create test file
                copy:
                  content: "Hello from Ansible!"
                  dest: /tmp/ansible-test/hello.txt
              
              - name: Read test file
                command: cat /tmp/ansible-test/hello.txt
                register: file_content
              
              - name: Show file content
                debug:
                  var: file_content.stdout
          EOF

      - name: Create inventory
        run: |
          mkdir -p inventory
          echo "localhost ansible_connection=local" > inventory/hosts

      - name: Check playbook syntax
        run: ansible-playbook playbooks/test.yml --syntax-check

      - name: Run playbook
        run: ansible-playbook -i inventory/hosts playbooks/test.yml
