name: Ansible Test Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-ansible:
    name: Test Ansible Playbooks
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # Remove cache option since we don't have requirements.txt yet
          
      - name: Create requirements file
        run: |
          cat << EOF > requirements.txt
          ansible>=8.0.0
          ansible-lint>=6.0.0
          yamllint>=1.26.0
          molecule>=5.0.0
          molecule-docker>=2.0.0
          EOF

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Display Ansible version
        run: |
          ansible --version
          ansible-lint --version

      - name: Create test inventory
        run: |
          mkdir -p tests/inventory
          echo "localhost ansible_connection=local" > tests/inventory/hosts

      - name: Create test playbook
        run: |
          mkdir -p tests/playbooks
          cat << EOF > tests/playbooks/test.yml
          ---
          - name: Test playbook
            hosts: localhost
            gather_facts: false
            tasks:
              - name: Print hello
                debug:
                  msg: "Hello from Ansible in GitHub Actions!"
              
              - name: Check Python
                command: python --version
                register: python_version
              
              - name: Display Python version
                debug:
                  var: python_version.stdout
          EOF

      - name: Lint playbooks
        run: |
          ansible-lint tests/playbooks/*.yml || true

      - name: Check playbook syntax
        run: |
          ansible-playbook tests/playbooks/test.yml --syntax-check

      - name: Run test playbook
        run: |
          ansible-playbook -i tests/inventory/hosts tests/playbooks/test.yml
