name: Deploy EC2 Instance

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-west-2'
      instance_type:
        description: 'Instance Type'
        required: true
        default: 't2.micro'
      image_id:
        description: 'AMI ID'
        required: true
        default: 'ami-0c94755bb95c71c99'
      key_name:
        description: 'SSH Key Name'
        required: true
      security_group_name:
        description: 'Security Group Name'
        required: true
        default: 'allow-ssh'

jobs:

  deploy-ec2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.aws_region }}

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Retrieve Subnet ID
      id: subnet
      run: |
        SUBNET_ID=$(ansible-playbook -i localhost, ec2-deploy.yml \
          -e "aws_region=${{ github.event.inputs.aws_region }}" \
          --task-timeout=1800 | grep '"id"' | awk -F'"' '{print $4}')
        echo "Subnet ID: $SUBNET_ID"
        echo "::set-output name=subnet_id::$SUBNET_ID"

    - name: Validate subnet availability
      run: |
        if [ -z "${{ steps.subnet.outputs.subnet_id }}" ]; then
          echo "No available subnets found in region ${{ github.event.inputs.aws_region }}"
          exit 1
        fi

    - name: Deploy EC2 Instance
      env:
        AWS_REGION: ${{ github.event.inputs.aws_region }}
        INSTANCE_TYPE: ${{ github.event.inputs.instance_type }}
        IMAGE_ID: ${{ github.event.inputs.image_id }}
        KEY_NAME: ${{ github.event.inputs.key_name }}
        SECURITY_GROUP_NAME: ${{ github.event.inputs.security_group_name }}
        SUBNET_ID: ${{ steps.subnet.outputs.subnet_id }}
      run: |
        ansible-playbook -i localhost, ec2-deploy.yml \
          -e "aws_region=$AWS_REGION" \
          -e "instance_type=$INSTANCE_TYPE" \
          -e "image_id=$IMAGE_ID" \
          -e "key_name=$KEY_NAME" \
          -e "security_group_name=$SECURITY_GROUP_NAME" \
          -e "subnet_id=$SUBNET_ID"
      # Catch any errors and provide additional context
      continue-on-error: true
      if: failure()
      run: |
        echo "An error occurred while deploying the EC2 instance."
        echo "Playbook output:"
        cat ec2-deploy.yml.log
        exit 1
